# Generated by Django 4.2.15 on 2024-08-21 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Maestro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ma_codigo", models.CharField(max_length=50)),
                ("ma_nombre", models.CharField(max_length=100)),
                ("ma_descripcion", models.TextField(blank=True, null=True)),
                ("ma_is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Codigo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("co_codigo", models.CharField(max_length=50)),
                ("co_nombre", models.CharField(max_length=100)),
                ("co_descripcion", models.TextField(blank=True, null=True)),
                ("co_param1", models.CharField(blank=True, max_length=100, null=True)),
                ("co_param2", models.CharField(blank=True, max_length=100, null=True)),
                ("co_is_active", models.BooleanField(default=True)),
                (
                    "ma_idma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="authentication.maestro",
                    ),
                ),
            ],
        ),
    ]
