# Generated by Django 4.2.15 on 2024-08-22 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authentication", "0002_maestro_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("nivel", models.PositiveIntegerField(default=1)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Clase CSS para el ícono (por ejemplo, 'fa fa-home').",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el elemento del menú está activo o no.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(related_name="menu_items", to="auth.group"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="authentication.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["nivel", "order"],
            },
        ),
    ]
